//! Time conversion helpers shared between `xml_builder` and the main
//! sidecar handler.
//!
//! The XML `<TS>` element (Kyiv-local `YYYYMMDDHHMMSS` digits) and the
//! gRPC `Check.date_time` (Kyiv-local-as-epoch integer) must match the
//! same business_ts — otherwise the signed document body and the
//! transport envelope disagree and DPS rejects the submission.
//!
//! IMPORTANT: Ukraine's IANA tzdata `Europe/Kyiv` STILL applies DST
//! (UTC+2 winter, UTC+3 summer) even though a 2022 Ukrainian law
//! declared permanent UTC+3.  Python's `zoneinfo('Europe/Kyiv')`
//! follows IANA, so Rust must too — otherwise winter (Oct–Mar) docs
//! produce divergent timestamps between the two code paths.  This
//! module uses `time-tz` (IANA-backed).

use time::{format_description::well_known::Rfc3339, OffsetDateTime};
use time_tz::{timezones, OffsetDateTimeExt, PrimitiveDateTimeExt};

use crate::errors::SidecarError;

/// Parse a `business_ts` ISO-8601 UTC string.  Accepts both full
/// RFC3339 and bare ISO-8601 without timezone (treated as UTC).
pub fn parse_business_ts(business_ts: &str) -> Result<OffsetDateTime, SidecarError> {
    OffsetDateTime::parse(business_ts, &Rfc3339)
        .or_else(|_| {
            let with_z = format!("{business_ts}Z");
            OffsetDateTime::parse(&with_z, &Rfc3339)
        })
        .map_err(|e| {
            SidecarError::BadRequest(format!(
                "invalid business_ts {:?}: {}", business_ts, e
            ))
        })
}

/// Kyiv-local wall-clock expressed as a Unix epoch.
///
/// Mirrors Python `_kyiv_local_epoch`
/// (`transports/dps_fiscal_server.py:54-69`): convert the UTC instant
/// to Europe/Kyiv local time, then re-interpret those wall-clock
/// digits as if they were UTC and take the resulting epoch.  DPS
/// expects this value in `Check.date_time` to match the XML `<TS>`
/// digits in the signed document.
pub fn kyiv_local_epoch(business_ts: &str) -> Result<i64, SidecarError> {
    let odt = parse_business_ts(business_ts)?;
    let kyiv = timezones::db::europe::KYIV;
    let kyiv_dt = odt.to_timezone(kyiv);
    // Extract Kyiv wall-clock y/m/d/H/M/S and re-interpret as UTC to
    // get the "local-digits-as-epoch" value DPS expects.
    let kyiv_pdt = time::PrimitiveDateTime::new(kyiv_dt.date(), kyiv_dt.time());
    let fake_utc = kyiv_pdt.assume_utc();
    Ok(fake_utc.unix_timestamp())
}

/// Kyiv-local wall-clock as `YYYYMMDDHHMMSS` ASCII digits — matches
/// the XML `<TS>` convention used throughout the DPS protocol.
pub fn kyiv_local_yyyymmddhhmmss(business_ts: &str) -> Result<String, SidecarError> {
    let odt = parse_business_ts(business_ts)?;
    let kyiv = timezones::db::europe::KYIV;
    let kyiv_dt = odt.to_timezone(kyiv);
    Ok(format!(
        "{year:04}{month:02}{day:02}{hour:02}{minute:02}{second:02}",
        year = kyiv_dt.year(),
        month = kyiv_dt.month() as u8,
        day = kyiv_dt.day(),
        hour = kyiv_dt.hour(),
        minute = kyiv_dt.minute(),
        second = kyiv_dt.second(),
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_accepts_rfc3339_with_z() {
        parse_business_ts("2026-04-21T10:15:30Z").unwrap();
    }

    #[test]
    fn parse_accepts_rfc3339_with_explicit_offset() {
        parse_business_ts("2026-04-21T10:15:30+00:00").unwrap();
    }

    #[test]
    fn parse_tolerates_bare_iso8601_as_utc() {
        parse_business_ts("2026-04-21T10:15:30").unwrap();
    }

    #[test]
    fn parse_rejects_malformed_input() {
        let err = parse_business_ts("not a date").unwrap_err();
        assert!(matches!(err, SidecarError::BadRequest(_)));
    }

    #[test]
    fn kyiv_epoch_summer_is_utc_plus_three() {
        // April (DST active): UTC+3.
        let utc_ts = parse_business_ts("2026-04-21T10:15:30Z")
            .unwrap()
            .unix_timestamp();
        let kyiv_ep = kyiv_local_epoch("2026-04-21T10:15:30Z").unwrap();
        assert_eq!(kyiv_ep - utc_ts, 3 * 3600);
    }

    #[test]
    fn kyiv_epoch_winter_is_utc_plus_two() {
        // January (DST inactive, winter UTC+2): regression guard
        // against the "permanent UTC+3" assumption from xml_builder.
        let utc_ts = parse_business_ts("2026-01-15T10:15:30Z")
            .unwrap()
            .unix_timestamp();
        let kyiv_ep = kyiv_local_epoch("2026-01-15T10:15:30Z").unwrap();
        assert_eq!(kyiv_ep - utc_ts, 2 * 3600);
    }

    #[test]
    fn kyiv_epoch_matches_python_reference_vectors() {
        // Reference values generated by Python's _kyiv_local_epoch
        // for the same UTC inputs — Rust MUST return identical values.
        for (iso, expected) in [
            ("2026-04-21T10:15:30Z", 1776777330_i64),  // summer UTC+3
            ("2026-01-01T00:00:00Z", 1767232800_i64),  // winter UTC+2
            ("2026-12-31T23:59:59Z", 1798768799_i64),  // winter UTC+2
        ] {
            let got = kyiv_local_epoch(iso).unwrap();
            assert_eq!(got, expected,
                "kyiv_local_epoch({}) = {}, expected {}", iso, got, expected);
        }
    }

    #[test]
    fn kyiv_epoch_is_deterministic() {
        let a = kyiv_local_epoch("2026-04-21T10:15:30Z").unwrap();
        std::thread::sleep(std::time::Duration::from_millis(50));
        let b = kyiv_local_epoch("2026-04-21T10:15:30Z").unwrap();
        assert_eq!(a, b);
    }

    #[test]
    fn kyiv_epoch_rejects_invalid_input_not_substitutes_now() {
        let err = kyiv_local_epoch("malformed").unwrap_err();
        assert!(matches!(err, SidecarError::BadRequest(_)));
    }

    #[test]
    fn kyiv_yyyymmddhhmmss_summer() {
        // UTC 10:15:30 in April → Kyiv 13:15:30.
        let s = kyiv_local_yyyymmddhhmmss("2026-04-21T10:15:30Z").unwrap();
        assert_eq!(s, "20260421131530");
    }

    #[test]
    fn kyiv_yyyymmddhhmmss_winter() {
        // UTC 10:15:30 in January → Kyiv 12:15:30 (UTC+2, winter).
        let s = kyiv_local_yyyymmddhhmmss("2026-01-15T10:15:30Z").unwrap();
        assert_eq!(s, "20260115121530");
    }

    #[test]
    fn kyiv_epoch_dst_spring_forward_transition() {
        // Europe/Kyiv DST starts last Sunday of March at 03:00 local
        // (01:00 UTC → jumps to 02:00 UTC = Kyiv 03:00 UTC+3).  We test
        // before and after the jump to catch a +2/+3 misclassification.
        let before = kyiv_local_epoch("2026-03-29T00:59:59Z").unwrap();
        let after = kyiv_local_epoch("2026-03-29T01:00:00Z").unwrap();
        // Before: UTC+2 offset → 00:59:59 UTC + 2h = 02:59:59 Kyiv
        // After:  UTC+3 offset → 01:00:00 UTC + 3h = 04:00:00 Kyiv
        let before_utc = parse_business_ts("2026-03-29T00:59:59Z").unwrap().unix_timestamp();
        let after_utc = parse_business_ts("2026-03-29T01:00:00Z").unwrap().unix_timestamp();
        assert_eq!(before - before_utc, 2 * 3600, "pre-spring-forward must be UTC+2");
        assert_eq!(after - after_utc, 3 * 3600, "post-spring-forward must be UTC+3");
    }

    #[test]
    fn kyiv_epoch_dst_fall_back_transition() {
        // Last Sunday of October at 04:00 local (01:00 UTC) rolls back
        // to 03:00 local (01:00 UTC = Kyiv 03:00 UTC+2).  Before the
        // jump we're at UTC+3, after — UTC+2.
        let before_utc = parse_business_ts("2026-10-25T00:59:59Z").unwrap().unix_timestamp();
        let after_utc = parse_business_ts("2026-10-25T01:00:00Z").unwrap().unix_timestamp();
        let before = kyiv_local_epoch("2026-10-25T00:59:59Z").unwrap();
        let after = kyiv_local_epoch("2026-10-25T01:00:00Z").unwrap();
        assert_eq!(before - before_utc, 3 * 3600, "pre-fall-back must be UTC+3");
        assert_eq!(after - after_utc, 2 * 3600, "post-fall-back must be UTC+2");
    }

    #[test]
    fn kyiv_yyyymmddhhmmss_year_boundary_winter() {
        // Kyiv winter UTC+2: 22:00 UTC 31-Dec → 00:00 Kyiv 1-Jan next year.
        let s = kyiv_local_yyyymmddhhmmss("2026-12-31T22:00:00Z").unwrap();
        assert_eq!(s, "20270101000000");
    }

    #[test]
    fn kyiv_yyyymmddhhmmss_year_boundary_summer() {
        // Kyiv summer UTC+3: 21:00 UTC 31-Dec is still 23:59:59 Kyiv
        // (but December is winter; use July boundary instead).
        // July 31 23:59:59 UTC → Aug 1 02:59:59 Kyiv (UTC+3, summer).
        let s = kyiv_local_yyyymmddhhmmss("2026-07-31T23:59:59Z").unwrap();
        assert_eq!(s, "20260801025959");
    }
}
