<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Web Check</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="WebCheck">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/WebCheck.dll</HintPath>
    </Reference>
    <Reference Include="System.Data.SQLite">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/System.Data.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../../../../home/setter/.dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Xml.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>