-- 017 — M3b W14a-2b: `signed_by_cashier_id` column on `fiscal_documents`.
--
-- Per spec `docs/superpowers/specs/2026-05-19-w14a-2b-signer-channel.md`
-- §1.4 + §2.2.  Required for sign-time cashier enforcement (spec §16.8):
-- the operator/cashier id that signed a fiscal document is persisted on
-- the ledger row so that `signer_guard::enforce_signer_cashier_match`
-- (added in W14a-2b Commit 3) can compare against `shifts.opened_by_
-- cashier_id` BEFORE wire send.
--
-- NULLABLE — pre-W14a-2b ledger rows have no value; back-fill is NOT
-- attempted (no source for it).  Future M3c/M4 may add a back-fill
-- routine if a forensic-reconstruction surface lands.
--
-- No FK to a cashier registry — cross-FN binding is enforced at runtime
-- via the same `cashier_certs(cashier_id, fiscal_number)` existence
-- check that the W14a-2a senior-close seam uses (`senior_cashier_
-- close_shift_with_audit`).  Ledger-level FK would block legitimate
-- offline replay scenarios where the cashier cert was rotated after
-- the doc was issued (Pattern C drain time gap).
--
-- Scoped strictly to `rust/prro/migrations/`; root `sql/` (Python
-- historical contour) is untouched per W14a-2b scope freeze.

ALTER TABLE fiscal_documents ADD COLUMN signed_by_cashier_id TEXT;
