<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>WebCheck</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net461</TargetFramework>
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>11.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Data.SQLite">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/System.Data.SQLite.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml">
      <HintPath>../../../../../../home/setter/.dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Xml.dll</HintPath>
    </Reference>
    <Reference Include="TaxGrpc">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/TaxGrpc.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.S3">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/AWSSDK.S3.dll</HintPath>
    </Reference>
    <Reference Include="DotNetZip">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/DotNetZip.dll</HintPath>
    </Reference>
    <Reference Include="AWSSDK.Core">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/AWSSDK.Core.dll</HintPath>
    </Reference>
    <Reference Include="Gma.QrCodeNet.Encoding">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/Gma.QrCodeNet.Encoding.dll</HintPath>
    </Reference>
    <Reference Include="itextsharp">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/itextsharp.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceProcess">
      <HintPath>../../../../../../home/setter/.dotnet/shared/Microsoft.NETCore.App/6.0.36/System.ServiceProcess.dll</HintPath>
    </Reference>
    <Reference Include="posnet">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/posnet.dll</HintPath>
    </Reference>
    <Reference Include="EUSignCPWebCheck">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/EUSignCPWebCheck.dll</HintPath>
    </Reference>
    <Reference Include="System.Core">
      <HintPath>../../../../../../home/setter/.dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>../../../../../c/Program Files (x86)/WebCheck/PRRO32/Newtonsoft.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Http">
      <HintPath>../../../../../../home/setter/.dotnet/shared/Microsoft.NETCore.App/6.0.36/System.Net.Http.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>