# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import fiscal_server_pb2 as fiscal__server__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fiscal_server_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChkIncomeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendChkV2 = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/sendChkV2',
                request_serializer=fiscal__server__pb2.Check.SerializeToString,
                response_deserializer=fiscal__server__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.lastChk = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/lastChk',
                request_serializer=fiscal__server__pb2.CheckRequest.SerializeToString,
                response_deserializer=fiscal__server__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/ping',
                request_serializer=fiscal__server__pb2.Check.SerializeToString,
                response_deserializer=fiscal__server__pb2.CheckResponse.FromString,
                _registered_method=True)
        self.statusRro = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/statusRro',
                request_serializer=fiscal__server__pb2.CheckRequest.SerializeToString,
                response_deserializer=fiscal__server__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.infoRro = channel.unary_unary(
                '/com.programika.rro.ws.chk.ChkIncomeService/infoRro',
                request_serializer=fiscal__server__pb2.CheckRequest.SerializeToString,
                response_deserializer=fiscal__server__pb2.RroInfoResponse.FromString,
                _registered_method=True)


class ChkIncomeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sendChkV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lastChk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def statusRro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def infoRro(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChkIncomeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendChkV2': grpc.unary_unary_rpc_method_handler(
                    servicer.sendChkV2,
                    request_deserializer=fiscal__server__pb2.Check.FromString,
                    response_serializer=fiscal__server__pb2.CheckResponse.SerializeToString,
            ),
            'lastChk': grpc.unary_unary_rpc_method_handler(
                    servicer.lastChk,
                    request_deserializer=fiscal__server__pb2.CheckRequest.FromString,
                    response_serializer=fiscal__server__pb2.CheckResponse.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=fiscal__server__pb2.Check.FromString,
                    response_serializer=fiscal__server__pb2.CheckResponse.SerializeToString,
            ),
            'statusRro': grpc.unary_unary_rpc_method_handler(
                    servicer.statusRro,
                    request_deserializer=fiscal__server__pb2.CheckRequest.FromString,
                    response_serializer=fiscal__server__pb2.StatusResponse.SerializeToString,
            ),
            'infoRro': grpc.unary_unary_rpc_method_handler(
                    servicer.infoRro,
                    request_deserializer=fiscal__server__pb2.CheckRequest.FromString,
                    response_serializer=fiscal__server__pb2.RroInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.programika.rro.ws.chk.ChkIncomeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.programika.rro.ws.chk.ChkIncomeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChkIncomeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sendChkV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/sendChkV2',
            fiscal__server__pb2.Check.SerializeToString,
            fiscal__server__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lastChk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/lastChk',
            fiscal__server__pb2.CheckRequest.SerializeToString,
            fiscal__server__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/ping',
            fiscal__server__pb2.Check.SerializeToString,
            fiscal__server__pb2.CheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def statusRro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/statusRro',
            fiscal__server__pb2.CheckRequest.SerializeToString,
            fiscal__server__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def infoRro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.programika.rro.ws.chk.ChkIncomeService/infoRro',
            fiscal__server__pb2.CheckRequest.SerializeToString,
            fiscal__server__pb2.RroInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
