//! `PRRO_GATE-0ps` — the DPS RPC surface is a DECIDED surface, not an accident.
//!
//! WebCheck's decompiled `TaxGrpc` generates EIGHT unary RPCs; we implement FIVE.
//! The three we do not implement were each deferred by an explicit decision
//! recorded in `docs/superpowers/specs/2026-07-31-adr-dps-rpc-surface.md`:
//!
//! - `sendChk` (API v1) — DEFERRED; we are v2-only, and an `apiver=1` config is
//!   REFUSED, never silently migrated.
//! - `delLastChk` / `delLastChkId` — DEFERRED to `PRRO_GATE-2pz` (P3); they are
//!   DESTRUCTIVE admin ops and our ledger invariants assume append-only.
//!
//! This is the tooth on that decision.  Adding any of them — or dropping one of
//! the five — turns this RED, so the ADR gets revisited instead of the surface
//! drifting in silently under a "just wire the RPC" commit.
//!
//! Why a text scan of the `.proto` rather than a type-level assertion: the proto
//! is the wire contract's single source of truth, `tonic` generates the client
//! from it, and a generated-but-unused RPC would still be a shipped capability.
//! The scan sees exactly what the code generator sees.

/// The proto is compiled by `build.rs`; pinning its TEXT pins what tonic emits.
const PROTO: &str = include_str!("../proto/fiscal_server.proto");

/// The five RPCs we implement, in declaration order.  Order is not load-bearing
/// for the wire; it is asserted only so the diff of a change is readable.
const IMPLEMENTED: [&str; 5] = ["sendChkV2", "lastChk", "ping", "statusRro", "infoRro"];

/// Generated by WebCheck's TaxGrpc but deliberately ABSENT from our proto.
/// `sendChk` is API v1; the `delLast*` pair is the destructive admin surface.
const DELIBERATELY_ABSENT: [&str; 3] = ["sendChk ", "delLastChk", "delLastChkId"];

fn declared_rpcs() -> Vec<String> {
    PROTO
        .lines()
        .map(str::trim)
        .filter_map(|l| l.strip_prefix("rpc "))
        .filter_map(|rest| rest.split_whitespace().next())
        .map(str::to_string)
        .collect()
}

#[test]
fn the_dps_rpc_surface_is_exactly_the_five_decided_ones() {
    let declared = declared_rpcs();
    assert_eq!(
        declared, IMPLEMENTED,
        "the DPS RPC surface changed.  It is a DECIDED surface (ADR \
         2026-07-31-adr-dps-rpc-surface, bd PRRO_GATE-0ps): adding or removing an \
         RPC needs that ADR revisited first — especially `sendChk` (API v1) and \
         the destructive `delLast*` pair."
    );
}

#[test]
fn the_deferred_rpcs_are_absent() {
    for name in DELIBERATELY_ABSENT {
        assert!(
            !PROTO.contains(&format!("rpc {name}")),
            "`{}` appeared in the proto.  It is DEFERRED by ADR \
             2026-07-31-adr-dps-rpc-surface: `sendChk` is API v1 (we are v2-only; \
             an apiver=1 config is refused, not migrated) and `delLastChk`/\
             `delLastChkId` are DESTRUCTIVE admin ops that contradict our \
             append-only ledger invariants.  Wiring one needs the ADR updated and \
             — for the delLast* pair — the `PRRO_GATE-2pz` probe answered FIRST \
             (does a DPS-side deletion leave a hole in the numbering or the MAC \
             chain?).",
            name.trim()
        );
    }
}

/// The API version is expressed by WHICH submit RPC we call — there is no
/// `verAPI` field on our wire (it appears nowhere in `src/`, only in two prose
/// comments).  WebCheck carries it as a client parameter that PICKS the RPC
/// (`TaxGrpc/Client.cs:57,114`), defaulting to 2 (`WebCheck/All.cs:20`,
/// `ClassFiscal.cs:69`).  So "we are verAPI=2" is exactly the statement
/// "the only submit RPC we own is `sendChkV2`" — which is what this asserts.
#[test]
fn the_only_submit_rpc_is_the_v2_one() {
    let submits: Vec<String> = declared_rpcs()
        .into_iter()
        .filter(|r| r.starts_with("sendChk"))
        .collect();
    assert_eq!(
        submits,
        vec!["sendChkV2".to_string()],
        "there must be EXACTLY ONE submit RPC and it must be the v2 one — a \
         second submit path would mean a runtime version choice (WebCheck's \
         `verAPI`) that we deliberately do not have"
    );
}
