//! Byte-identical proof against jkurwa test vectors.
//!
//! This test consumes vectors generated by scripts/extract_gf2m_vectors.js
//! using the Node.js jkurwa library. Each vector pairs an operation with its
//! expected result; we run the Rust port and verify byte-level parity.
//!
//! If any vector fails, the implementation has diverged from jkurwa — this
//! is the authoritative correctness check for GF(2^m) arithmetic.

use serde::Deserialize;

use prro_crypto::core::gf2m::{blength, finv, fmod, fmul, mul_2x2};

#[derive(Debug, Deserialize)]
#[serde(tag = "op")]
enum Vector {
    #[serde(rename = "mul")]
    Mul {
        a: String,
        b: String,
        a_words: usize,
        b_words: usize,
        expected: String,
        expected_words: usize,
    },
    #[serde(rename = "mod")]
    Mod {
        a: String,
        a_words: usize,
        p_exp: Vec<u32>,
        expected: String,
        expected_words: usize,
    },
    #[serde(rename = "inv")]
    Inv {
        a: String,
        a_words: usize,
        p_bits: String,
        p_words: usize,
        expected: String,
        expected_words: usize,
    },
    #[serde(rename = "blength")]
    Blength {
        a: String,
        a_words: usize,
        expected: u32,
    },
    #[serde(rename = "mul_2x2")]
    Mul2x2 {
        a0: u32,
        a1: u32,
        b0: u32,
        b1: u32,
        expected: [u32; 4],
    },
}

/// Convert big-endian hex string to little-endian u32 array.
fn hex_to_words(hex: &str, words: usize) -> Vec<u32> {
    let mut padded = String::new();
    let needed = words * 8;
    if hex.len() < needed {
        padded.extend(std::iter::repeat('0').take(needed - hex.len()));
        padded.push_str(hex);
    } else {
        padded.push_str(hex);
    }
    let bytes = hex::decode(&padded).expect("invalid hex");
    // bytes is big-endian; we want little-endian u32 words.
    // word[i] (LE) is at bytes positions [(words-1-i)*4 .. (words-i)*4]
    let mut out = vec![0u32; words];
    for i in 0..words {
        let start = (words - 1 - i) * 4;
        let chunk = &bytes[start..start + 4];
        out[i] = u32::from_be_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]);
    }
    out
}

fn words_to_hex(v: &[u32]) -> String {
    let mut s = String::new();
    for i in (0..v.len()).rev() {
        s.push_str(&format!("{:08x}", v[i]));
    }
    s
}

fn load_vectors() -> Vec<Vector> {
    let json = include_str!("vectors/gf2m_jkurwa.json");
    serde_json::from_str(json).expect("vectors/gf2m_jkurwa.json malformed")
}

#[test]
fn test_against_jkurwa_vectors() {
    let vectors = load_vectors();
    assert!(!vectors.is_empty(), "no vectors loaded");

    let mut counts: std::collections::HashMap<&str, (usize, usize)> = std::collections::HashMap::new();
    let mut failures: Vec<String> = Vec::new();

    for (idx, v) in vectors.iter().enumerate() {
        let (op_name, ok, detail) = match v {
            Vector::Mul {
                a,
                b,
                a_words,
                b_words,
                expected,
                expected_words,
            } => {
                let aw = hex_to_words(a, *a_words);
                let bw = hex_to_words(b, *b_words);
                let mut s = vec![0u32; *expected_words];
                fmul(&aw, &bw, &mut s);
                let got_hex = words_to_hex(&s);
                (
                    "mul",
                    &got_hex == expected,
                    format!("expected {}, got {}", expected, got_hex),
                )
            }
            Vector::Mod {
                a,
                a_words,
                p_exp,
                expected,
                expected_words,
            } => {
                let aw = hex_to_words(a, *a_words);
                let mut ret = vec![0u32; *expected_words];
                fmod(&aw, p_exp, &mut ret);
                let got_hex = words_to_hex(&ret);
                (
                    "mod",
                    &got_hex == expected,
                    format!("expected {}, got {}", expected, got_hex),
                )
            }
            Vector::Inv {
                a,
                a_words,
                p_bits,
                p_words,
                expected,
                expected_words,
            } => {
                let aw = hex_to_words(a, *a_words);
                let pw = hex_to_words(p_bits, *p_words);
                let mut ret = vec![0u32; *expected_words];
                finv(&aw, &pw, &mut ret);
                let got_hex = words_to_hex(&ret);
                (
                    "inv",
                    &got_hex == expected,
                    format!("expected {}, got {}", expected, got_hex),
                )
            }
            Vector::Blength {
                a,
                a_words,
                expected,
            } => {
                let aw = hex_to_words(a, *a_words);
                let got = blength(&aw);
                (
                    "blength",
                    got == *expected,
                    format!("expected {}, got {}", expected, got),
                )
            }
            Vector::Mul2x2 {
                a0,
                a1,
                b0,
                b1,
                expected,
            } => {
                let got = mul_2x2(*a1, *a0, *b1, *b0);
                (
                    "mul_2x2",
                    got == *expected,
                    format!("expected {:?}, got {:?}", expected, got),
                )
            }
        };

        let entry = counts.entry(op_name).or_insert((0, 0));
        entry.0 += 1;
        if ok {
            entry.1 += 1;
        } else {
            failures.push(format!("vector #{} ({}): {}", idx, op_name, detail));
        }
    }

    eprintln!("\n=== Vector results ===");
    for (op, (total, passed)) in &counts {
        eprintln!("  {}: {}/{}", op, passed, total);
    }

    if !failures.is_empty() {
        eprintln!("\n=== First 10 failures ===");
        for f in failures.iter().take(10) {
            eprintln!("  {}", f);
        }
        panic!("{} of {} vectors failed", failures.len(), vectors.len());
    }
}
